version: "3.7"

services:

    fastify_api:
        build:
            context: ./fastify_api
            dockerfile: Dockerfile
        container_name: fastify_api
        # environment: 
        #     # uri params also used to configure connection options
        #     DB_URI: ${MONGO_DB_URI}
        #     DB_NAME: ${MONGO_DB_PACKETS}
        volumes:
            - type: bind
              source: ./fastify_api/
              target: /app 
        ports:
            - 3000:3000
        restart: always
        depends_on: 
            - mongo_db 

    mongo_db:
        build:
            context: ./mongo_db
            dockerfile: Dockerfile
        container_name: mongo_db
        #environment: 
        #    MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
        #    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
        volumes:
            - type: bind
              source: .devdatabase/
              target: /data/db
        ports:
            -  27017:27017
        restart: always
